language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mattfrancis/multi-docker-test -f Dockerfile.dev .
# tag is only used in travis, not related to tags in our local computer
script:
    - docker run -e CI=true mattfrancis/multi-docker-test npm run test -- --coverage
# we run dockerfile.dev because dockerfile.dev allows tests suites to run

deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app: multi-docker-project
#https://travis-ci.community/t/failed-to-deploy-heroku-api-request-failed-message-invalid-credentials-provided/9988/4
