version: "3"
services:
    web:
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            #don't touch /app/node_modules
            - .:/app
            #copy everything in our local files to app
#We are usign docker compose here for volumes
