version: "3"
services:
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "3050:80"
    client:
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        # ports:
        #     - "3000:3000"
        volumes:
            - /app/node_modules
            #don't touch /app/node_modules
            - ./client:/app
            #copy everything in our local files to app
    api:
        environment:
            - CHOKIDAR_USEPOLLING=true
            - user
            - database
            - password
            - elephantSQLUser
            - elephantSQLServer
            - elephantSQLDatabase
            - elephantSQLPassword
        #nodemon will not work without chokidar
        #https://github.com/remy/nodemon/issues/1802
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        # ports:
        #     - "5000:5000"
        volumes:
            - /app/node_modules
            - ./server:/app
#We are usign docker compose here for volumes
